# Generated by Django 5.2.7 on 2025-10-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=50, verbose_name='Nombre Area')),
                ('nombre_area_corto', models.CharField(max_length=50, verbose_name='Nombre Area Corto')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
                'constraints': [models.UniqueConstraint(fields=('nombre_area', 'nombre_area_corto'), name='constrains_area')],
            },
        ),
    ]
