# Generated by Django 5.2.7 on 2025-10-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Completo')),
                ('tipo_documento', models.CharField(choices=[('1', 'Cedula'), ('2', 'Pasaporte'), ('3', 'Cedula Extranjeria'), ('4', 'Permiso Especial de Permanencia')], max_length=1, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profesion', models.CharField(choices=[('1', 'Abogado'), ('2', 'Ingeniero Sistemas'), ('3', 'Contador'), ('4', 'Tecnologo Sistemas'), ('5', 'Profesion Seguridad Salud Trabajo'), ('6', 'Publisista'), ('7', 'Tecnolgo Gestion Administrativa')], max_length=1, verbose_name='Profesion')),
                ('cargo', models.CharField(choices=[('1', 'Auxiliar'), ('2', 'Tecnico'), ('3', 'Tecnologo'), ('4', 'Profesional'), ('5', 'Especialista'), ('6', 'Director'), ('7', 'Gerente')], max_length=1, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Fotos', verbose_name='Foto')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_empleado', to='area.area')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'constraints': [models.UniqueConstraint(fields=('nombres', 'apellidos', 'numero_documento'), name='unique_empleado')],
            },
        ),
    ]
